app = "app-nkizyevt"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[env]
  DATABASE_PATH = "/data/docboxrx.db"
  DATABASE_URL = "postgresql://neondb_owner:npg_Z60uvbwqlBzk@ep-mute-hill-adb7l32q-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require"

[[mounts]]
  source = "docboxrx_data"
  destination = "/data"
